sylius_fixtures:
    suites:
        poland:
            fixtures:
                currency:
                    options:
                        currencies: ['PLN']

                geographical:
                    options:
                        countries:
                            - "PL"
                        zones:
                            PL:
                                name: "Poland"
                                countries:
                                    - "PL"

                channel:
                    options:
                        custom:
                            pl_web_store:
                                name: "PL Web Store"
                                code: "PL_WEB"
                                locales:
                                    - "%locale%"
                                currencies:
                                    - "PLN"
                                enabled: true
                                hostname: "localhost"

                shipping_method:
                    options:
                        custom:
                            inpost:
                                code: "inpost"
                                name: "InPost"
                                channels:
                                    - "PL_WEB"
                                zone: "PL"
